<?php

include_once dirname(__FILE__) . '/domain.inc';
include_once dirname(__FILE__) . '/hooks.inc';

/**
 * Implementation of hook_schema_alter().
 * Makes the domain tables usable by ctools' export.inc.
 */
function domain_export_schema_alter(&$schema) {

  /* Do not want to use sitename or subdomain as it can change
   */
  $schema['domain']['fields']['machine_name'] = array(
    'type' => 'varchar',
    'length' => '255',
    'description' => 'Unique ID for this object. Used to identify it programmatically.',
  );
  $schema['domain']['fields']['domain_id']['no export'] = TRUE ;
   /* Notifies ctools
   */
  $schema['domain']['export'] = array(
    'key' => 'machine_name',
    'status' => 'valid',
    'list callback' => 'domain_export_domain_list',
    'export callback' => 'domain_export_domain_export',
    'api' => array(
      'owner' => 'domain',
      'api' => 'domain',
      'minimum_version' => 1,
      'current_version' => 1,
    ),
  );
  //$schema['variable']['fields']['value']['serialize'] = TRUE;
}


/**
* Implementation of hook_menu().
*/
function domain_export_menu() {
  $items['admin/build/domain/export/%domain_export_domain'] = array(
    'title' => 'Export domain record',
    'access arguments' => array('administer domains'),
    'type' => MENU_CALLBACK,
    'page callback' => 'domain_export_export_domain',
    'page arguments' => array(4),
  );
  $items['admin/build/domain/revert/%domain_export_domain'] = array(
    'title' => 'Revert domain record',
    'access arguments' => array('administer domains'),
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('domain_export_revert_domain',4),
  );
  return $items;
}


/**
 * Implement hook_domainlinks()
 */
function domain_export_domainlinks($domain) {
  if ($domain['domain_id'] > 0 && !empty($domain['machine_name'])) {
    $links[] = array(
      'title' => t('export'),
      'path' => 'admin/build/domain/export/'. $domain['machine_name']
    );
    $exported_domains = module_invoke_all('default_domain');
    if (!empty($exported_domains[$domain['machine_name']])) {
      $links[] = array(
        'title' => t('Revert'),
        'path' => 'admin/build/domain/revert/'. $domain['machine_name']
      );
    }
    return $links;
  }
  return FALSE;
}
