<?php

include_once dirname(__FILE__) . '/domain.inc';


/**
 * Implementation of hook_schema_alter().
 * Makes the domain tables usable by ctools' export.inc.
 */
function domain_export_schema_alter(&$schema) {

  /* Do not want to use sitename or subdomain as it can change
   */
  $schema['domain']['fields']['machine_name'] = array(
    'type' => 'varchar',
    'length' => '255',
    'description' => 'Unique ID for this object. Used to identify it programmatically.',
  );
  $schema['domain']['fields']['domain_id']['no export'] = TRUE ;
   /* Notifies ctools
   */
  $schema['domain']['export'] = array(
    'key' => 'machine_name',
    'status' => 'valid',
    'api' => array(
      'owner' => 'domain',
      'api' => 'domain',
      'minimum_version' => 1,
      'current_version' => 1,
    ),

  );
  //$schema['variable']['fields']['value']['serialize'] = TRUE;
}


/**
* Implementation of hook_menu().
*/
function domain_export_menu() {
  $items['admin/build/domain/export/%domain'] = array(
    'title' => 'Export domain record',
    'access arguments' => array('administer domains'),
    'type' => MENU_CALLBACK,
    'page callback' => 'domain_export_export_domain',
    'page arguments' => array(4),
  );
  return $items;
}


/**
 * Implement hook_domainlinks()
 */
function domain_export_domainlinks($domain) {
  if ($domain['domain_id'] > 0) {
    $links[] = array(
      'title' => t('export'),
      'path' => 'admin/build/domain/export/'. $domain['domain_id']
    );
    return $links;
  }
  return FALSE;
}

/*function domain_export_features_api() {
  return array(
    'domain' => array(
      'default_hook' => 'domain_defaults',
      'default_file' => FEATURES_DEFAULTS_INCLUDED,
      'features_source' => TRUE,
      'file' => drupal_get_path('module', 'domain_export') .'/domain_export.features.inc',
    ),
  )

}*/

